name: sellefli
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^5.0.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  font_awesome_flutter: ^10.12.0
  supabase_flutter: ^2.8.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  connectivity_plus: ^6.0.0
  uuid: ^4.5.2
  bloc: ^8.1.4
  meta: ^1.16.0
  sqflite: ^2.3.2
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.6
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
